### ISSUE TITLE
No longer working as of today - Firefox

### ISSUE THREAD

**Issue by Borkius** [euank/twitter-image-helper#14]
It looks like Twitter has blocked the extension. When I look at it in the extensions tabs it says "can't read or change data on this site". I use the latest update of Firefox, 126.0. I just got on twitter today and the extension no longer does anything. I disabled all other extensions and it still has no effect, the context menu is gone.

**Comment by euank** [comment]
Thanks for the report!

Are you getting redirected to x.com instead of twitter.com now, and it's failing there?

I tried to get the x.com thing working with `v0.9.0`, but I missed one change there (69eeee75a74f460bc54dd4dd41760c90e1bbcc27).

I just now release v0.9.1, which I'm hopeful will fix x.com properly. It seems to work for me.

So, for followup here, can you double check:

1. Is this issue on x.com, or twitter.com?
2. Does v0.9.1 work?

**Comment by Borkius** [comment]
Yep, I'm getting redirected to x.com now.
And yep the update fixed it!

**Comment by euank** [comment]
Glad to hear that fixed it, thanks again for the report!
